### ISSUE TITLE
Your Suggestions 

### ISSUE THREAD

**Issue by AD1TYA03** [AD1TYA03/eduForEveryone#1]
Hey I am Beginner in web development and it will be my pleasure learning from you guys

**Comment by ayushch80** [comment]
(1)  You may remove some unnecessary buttons or button which are not working well `login` `signup` `donate` `Get In Touch` `Work With Us`
(2) YT Videos are repeating 3 times
(3) CodeSandbox is slow so try hosting website from [replit](https://repl.it/)
