### ISSUE TITLE
Remove Repetative CSS 

### ISSUE THREAD

**Issue by AD1TYA03** [AD1TYA03/eduForEveryone#4]
Remove unnessasary css lines , but dont change functionalities , without informing

**Comment by DavidRod1865** [comment]
Hello! I'll like to give this one a try!

**Comment by asifurrahaman754** [comment]
@AD1TYA03 i just ran your project, i'll make a pr fixing this problem

**Comment by asifurrahaman754** [comment]
@AD1TYA03 please check my pr #7

**Comment by AD1TYA03** [comment]
All credits to @asifurrahaman754
